#!/bin/sh

# Author: Chi-Huy Trinh
# Version : 2019-10-03

# N.B. Windows user should use this with GitBash

# Copy this file (e.g. by symlink) in your local ./.git/hooks/
# folder as "pre-push". So every time you use '$ git push' command, your
# local project will be tested by the commands below first, as you
# would have done it manually yourself, prior pushing your code :
#
# $ npm install (update packages)
# $ npm test (test compilation and unit tests)
# $ npm lint (test lint)
#
# Once your code tested successfully, 'push' command will fire.
# But if any error occurs, it will abort and won't 'push'.

if [ -d server ]; then
	echo '>>cd server'
	cd server
fi

npm set progress=false

echo '>>npm installing'
# $ npm install (update packages)
npm install --prefer-offline

if [ "$?" -ne 0 ]; then
	exit 1;
fi

echo '>>npm "building"'
# (test compilation)
npm run tsc

if [ "$?" -ne 0 ]; then
	exit 1;
fi

echo '>>npm testing'
# $ npm run test (test unit tests)
npm run coverage_no_check

if [ "$?" -ne 0 ]; then
	exit 2;
fi

echo '>>npm linting'
# $ npm run lint (test lint)
npm run lint --fix

if [ "$?" -ne 0 ]; then
	exit 3;
fi

exit 0